/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgServicie;

import java.awt.Color;

/**
 *
 * @author Erick
 */
public class Servicies extends javax.swing.JFrame {

    /**
     * Creates new form Servicies
     */
    public Servicies() {
        initComponents();
        jPanelRegistrarServicio.setVisible(false);
        jPanelShowServices.setVisible(false);
        jTextFieldNewServicie.setBackground(new Color(0,0,0,0));
        jTextFieldNewServiciePrice.setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelServicie = new javax.swing.JPanel();
        jButtonMinimize = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jButtonShowService = new javax.swing.JButton();
        jButtonAddService = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanelShowServices = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanelRegistrarServicio = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNewServiciePrice = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldNewServicie = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelServicie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMinimize.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImgService/5.png"))); // NOI18N
        jButtonMinimize.setBorderPainted(false);
        jButtonMinimize.setContentAreaFilled(false);
        jButtonMinimize.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImgService/minus.png"))); // NOI18N
        jButtonMinimize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinimizeActionPerformed(evt);
            }
        });
        jPanelServicie.add(jButtonMinimize, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, -1, -1));

        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImgService/3.png"))); // NOI18N
        jButtonClose.setBorderPainted(false);
        jButtonClose.setContentAreaFilled(false);
        jButtonClose.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImgService/4.png"))); // NOI18N
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        jPanelServicie.add(jButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 0, -1, -1));

        jButtonShowService.setText("Mostrar Servicios");
        jButtonShowService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonShowServiceActionPerformed(evt);
            }
        });
        jPanelServicie.add(jButtonShowService, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        jButtonAddService.setText("Agregar Servicio");
        jButtonAddService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddServiceActionPerformed(evt);
            }
        });
        jPanelServicie.add(jButtonAddService, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Servicios");
        jPanelServicie.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, -1, -1));

        jPanelShowServices.setBackground(new java.awt.Color(255, 255, 255));
        jPanelShowServices.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanelShowServices.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 240));

        jPanelServicie.add(jPanelShowServices, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 480, 250));

        jPanelRegistrarServicio.setBackground(new java.awt.Color(255, 255, 255));
        jPanelRegistrarServicio.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setText("Precio :");
        jPanelRegistrarServicio.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 190, 40));

        jTextFieldNewServiciePrice.setBorder(null);
        jTextFieldNewServiciePrice.setOpaque(false);
        jTextFieldNewServiciePrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNewServiciePriceActionPerformed(evt);
            }
        });
        jPanelRegistrarServicio.add(jTextFieldNewServiciePrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 100, 250, 30));
        jPanelRegistrarServicio.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 260, 20));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel4.setText("Sercicio a agregar : ");
        jPanelRegistrarServicio.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 40));

        jTextFieldNewServicie.setBorder(null);
        jTextFieldNewServicie.setOpaque(false);
        jTextFieldNewServicie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNewServicieActionPerformed(evt);
            }
        });
        jPanelRegistrarServicio.add(jTextFieldNewServicie, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, 250, 30));
        jPanelRegistrarServicio.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 40, 260, 20));

        jPanelServicie.add(jPanelRegistrarServicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 460, 200));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pkgImgService/fondoPacient.png"))); // NOI18N
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanelServicie.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 430));

        getContentPane().add(jPanelServicie, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonShowServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonShowServiceActionPerformed
        jPanelShowServices.setVisible(true);
        jPanelRegistrarServicio.setVisible(false);
    }//GEN-LAST:event_jButtonShowServiceActionPerformed

    private void jButtonAddServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddServiceActionPerformed
        jPanelRegistrarServicio.setVisible(true);
        jPanelShowServices.setVisible(false);
    }//GEN-LAST:event_jButtonAddServiceActionPerformed

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonMinimizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinimizeActionPerformed
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButtonMinimizeActionPerformed

    private void jTextFieldNewServicieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNewServicieActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNewServicieActionPerformed

    private void jTextFieldNewServiciePriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNewServiciePriceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNewServiciePriceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Servicies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Servicies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Servicies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Servicies.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Servicies().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAddService;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonMinimize;
    private javax.swing.JButton jButtonShowService;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanelRegistrarServicio;
    private javax.swing.JPanel jPanelServicie;
    private javax.swing.JPanel jPanelShowServices;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextFieldNewServicie;
    private javax.swing.JTextField jTextFieldNewServiciePrice;
    // End of variables declaration//GEN-END:variables
}
