/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pckgEnvioFactura;

import Iinterfazes.iEnvioFactura;
import java.awt.Color;
import pckgMenu.MenuMain;

/**
 *
 * @author Erick
 */
public class FormMail extends javax.swing.JFrame {

    private int x, y;

    /**
     * Creates new form FormMail
     */
    public FormMail() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setBackground(new Color(0, 0, 0, 0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonMin = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jLabelCabecera = new javax.swing.JLabel();
        jPanelFondo = new javax.swing.JPanel();
        jLabelFileSubject = new javax.swing.JLabel();
        jLabelFileChooser = new javax.swing.JLabel();
        jLabelDestinatario = new javax.swing.JLabel();
        jLabelFileBody = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jTextFieldSubject = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jTextFieldDestinatario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jFileChooserFacturaPDF = new javax.swing.JFileChooser();
        jButtonSend = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaBody = new javax.swing.JTextArea();
        jCheckBoxOutlook = new javax.swing.JCheckBox();
        jCheckBoxGmail = new javax.swing.JCheckBox();
        jCheckBoxYahoo = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgMenu/imgs/min1.png"))); // NOI18N
        jButtonMin.setBorder(null);
        jButtonMin.setBorderPainted(false);
        jButtonMin.setContentAreaFilled(false);
        jButtonMin.setFocusPainted(false);
        jButtonMin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgMenu/imgs/min2.png"))); // NOI18N
        jButtonMin.setRolloverSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgMenu/imgs/min2.png"))); // NOI18N
        jButtonMin.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgMenu/imgs/min2.png"))); // NOI18N
        jButtonMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(775, 0, 60, 50));

        jButtonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgMenu/imgs/exit1.png"))); // NOI18N
        jButtonSalir.setBorder(null);
        jButtonSalir.setBorderPainted(false);
        jButtonSalir.setContentAreaFilled(false);
        jButtonSalir.setFocusPainted(false);
        jButtonSalir.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgMenu/imgs/exit2.png"))); // NOI18N
        jButtonSalir.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgMenu/imgs/exit2.png"))); // NOI18N
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(835, 0, 60, 50));

        jLabelCabecera.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jLabelCabecera.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCabecera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgMenu/imgs/barra.png"))); // NOI18N
        jLabelCabecera.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLabelCabecera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelCabeceraMouseDragged(evt);
            }
        });
        jLabelCabecera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelCabeceraMousePressed(evt);
            }
        });
        getContentPane().add(jLabelCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, -1));

        jPanelFondo.setBackground(new java.awt.Color(255, 255, 255));
        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelFileSubject.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabelFileSubject.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFileSubject.setText("Asunto: ");
        jPanelFondo.add(jLabelFileSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 130, 30));

        jLabelFileChooser.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabelFileChooser.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFileChooser.setText("Escoja Factura:");
        jPanelFondo.add(jLabelFileChooser, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 130, 30));

        jLabelDestinatario.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabelDestinatario.setForeground(new java.awt.Color(0, 0, 0));
        jLabelDestinatario.setText("Destinatario : ");
        jPanelFondo.add(jLabelDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 110, 30));

        jLabelFileBody.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabelFileBody.setForeground(new java.awt.Color(0, 0, 0));
        jLabelFileBody.setText("Mensaje: ");
        jPanelFondo.add(jLabelFileBody, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 130, 30));

        jSeparator3.setPreferredSize(new java.awt.Dimension(48, 10));
        jPanelFondo.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 580, 490, 10));

        jTextFieldSubject.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSubjectActionPerformed(evt);
            }
        });
        jPanelFondo.add(jTextFieldSubject, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 440, 490, 30));

        jSeparator2.setPreferredSize(new java.awt.Dimension(48, 10));
        jPanelFondo.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 480, 490, 10));
        jPanelFondo.add(jTextFieldDestinatario, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 490, 30));

        jSeparator1.setPreferredSize(new java.awt.Dimension(48, 10));
        jPanelFondo.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 490, 10));

        jFileChooserFacturaPDF.setCurrentDirectory(new java.io.File("C:\\Users\\allec\\Documents\\NetBeansProjects\\AnyDis2\\appClinicaDental\\AppClinicaDental\\src\\pckgReporte\\pdf"));
        jPanelFondo.add(jFileChooserFacturaPDF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, -1, 300));

        jButtonSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgEnvioFactura/imgs/buttonSendMail1.png"))); // NOI18N
        jButtonSend.setBorder(null);
        jButtonSend.setContentAreaFilled(false);
        jButtonSend.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSend.setDefaultCapable(false);
        jButtonSend.setFocusPainted(false);
        jButtonSend.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonSend.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgEnvioFactura/imgs/buttonSendMail2.png"))); // NOI18N
        jButtonSend.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgEnvioFactura/imgs/buttonSendMail2.png"))); // NOI18N
        jButtonSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSendActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonSend, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 490, -1, -1));

        jTextAreaBody.setColumns(20);
        jTextAreaBody.setRows(5);
        jScrollPane1.setViewportView(jTextAreaBody);

        jPanelFondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 490, 490, -1));

        jCheckBoxOutlook.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxOutlook.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jCheckBoxOutlook.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxOutlook.setText("Envio por Outlook");
        jCheckBoxOutlook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxOutlookActionPerformed(evt);
            }
        });
        jPanelFondo.add(jCheckBoxOutlook, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, -1, -1));

        jCheckBoxGmail.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxGmail.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jCheckBoxGmail.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxGmail.setText("Envio por Gmail");
        jCheckBoxGmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxGmailActionPerformed(evt);
            }
        });
        jPanelFondo.add(jCheckBoxGmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 60, -1, -1));

        jCheckBoxYahoo.setBackground(new java.awt.Color(255, 255, 255));
        jCheckBoxYahoo.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jCheckBoxYahoo.setForeground(new java.awt.Color(0, 0, 0));
        jCheckBoxYahoo.setText("Envio por Yahoo");
        jCheckBoxYahoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxYahooActionPerformed(evt);
            }
        });
        jPanelFondo.add(jCheckBoxYahoo, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, -1, -1));

        getContentPane().add(jPanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 900, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabelCabeceraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCabeceraMouseDragged
        //metodo para establecer la posicion de la ventana cuando se arrastre el boton por la cabecera
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jLabelCabeceraMouseDragged

    private void jLabelCabeceraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCabeceraMousePressed
        //metodo que obtiene cordenadas actuales del Frame mediante la cabecera
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabelCabeceraMousePressed

    private void jTextFieldSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSubjectActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSubjectActionPerformed

    private void jButtonMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinActionPerformed
        //minimizar el Frame Menu
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButtonMinActionPerformed

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
        dispose();
        MenuMain.menuVisible();
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jButtonSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSendActionPerformed
        if (jCheckBoxGmail.isSelected() == true) {
            iEnvioFactura envio = new EnvioGmail();
            envio.enviarFactura(jTextFieldDestinatario.getText(),
                    jTextFieldSubject.getText(), jTextAreaBody.getText(),
                    jFileChooserFacturaPDF.getSelectedFile());
        }

        if (jCheckBoxYahoo.isSelected() == true) {
            iEnvioFactura envio = new EnvioYahoo();
            envio.enviarFactura(jTextFieldDestinatario.getText(),
                    jTextFieldSubject.getText(), jTextAreaBody.getText(),
                    jFileChooserFacturaPDF.getSelectedFile());
        }
    }//GEN-LAST:event_jButtonSendActionPerformed

    private void jCheckBoxYahooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxYahooActionPerformed
        jCheckBoxGmail.setEnabled(false);
        jCheckBoxYahoo.setEnabled(false);
        jCheckBoxOutlook.setEnabled(false);
    }//GEN-LAST:event_jCheckBoxYahooActionPerformed

    private void jCheckBoxGmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxGmailActionPerformed
        jCheckBoxGmail.setEnabled(false);
        jCheckBoxYahoo.setEnabled(false);
        jCheckBoxOutlook.setEnabled(false);
    }//GEN-LAST:event_jCheckBoxGmailActionPerformed

    private void jCheckBoxOutlookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxOutlookActionPerformed
        jCheckBoxGmail.setEnabled(false);
        jCheckBoxYahoo.setEnabled(false);
        jCheckBoxOutlook.setEnabled(false);
    }//GEN-LAST:event_jCheckBoxOutlookActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMin;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JButton jButtonSend;
    private javax.swing.JCheckBox jCheckBoxGmail;
    private javax.swing.JCheckBox jCheckBoxOutlook;
    private javax.swing.JCheckBox jCheckBoxYahoo;
    private javax.swing.JFileChooser jFileChooserFacturaPDF;
    private javax.swing.JLabel jLabelCabecera;
    private javax.swing.JLabel jLabelDestinatario;
    private javax.swing.JLabel jLabelFileBody;
    private javax.swing.JLabel jLabelFileChooser;
    private javax.swing.JLabel jLabelFileSubject;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextArea jTextAreaBody;
    private javax.swing.JTextField jTextFieldDestinatario;
    private javax.swing.JTextField jTextFieldSubject;
    // End of variables declaration//GEN-END:variables
}
