/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pckgPaciente;

import Conexion.BDConnection;
import java.sql.*;
import java.awt.Color;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import pckgMenu.MenuMain;

/**
 *
 * @author allecc
 */
public class FramePatient extends javax.swing.JFrame {

    /**
     * Creates new form FramePatient FramePatient frame = new FramePatient();
     * frame.setInstance(instance); frame.setVisible(true); this.dispose();
     */
    DefaultTableModel modelPatient = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int col) {
            return col == 7;
        }
    };

    int x, y;

    AdminPatient administradoPaciente;

    public FramePatient() {
        initComponents();
        setPropertiesGUI();
        administradoPaciente = new AdminPatient();
//        setTablePatient(modelPatient);
        setTablePatient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonMin = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jLabelCabecera = new javax.swing.JLabel();
        jSeparatorFondo = new javax.swing.JSeparator();
        jPanelAgregarPaciente = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jTextFieldDPI = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jTextFieldNombre = new javax.swing.JTextField();
        jSeparator7 = new javax.swing.JSeparator();
        jTextFieldApellido = new javax.swing.JTextField();
        jTextFieldFechanac = new javax.swing.JTextField();
        jSeparator8 = new javax.swing.JSeparator();
        jTextFieldTel = new javax.swing.JTextField();
        jSeparator9 = new javax.swing.JSeparator();
        jTextFieldCel = new javax.swing.JTextField();
        jSeparator10 = new javax.swing.JSeparator();
        jButtonSaveDataPatient = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldDirec = new javax.swing.JTextField();
        jSeparator11 = new javax.swing.JSeparator();
        jPanelVerPaciente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePatient = new javax.swing.JTable();
        jPanelFondo = new javax.swing.JPanel();
        jButtonAdd = new javax.swing.JButton();
        jButtonVer = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/min1.png"))); // NOI18N
        jButtonMin.setBorder(null);
        jButtonMin.setBorderPainted(false);
        jButtonMin.setContentAreaFilled(false);
        jButtonMin.setFocusPainted(false);
        jButtonMin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/min2.png"))); // NOI18N
        jButtonMin.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/min2.png"))); // NOI18N
        jButtonMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 50, 50));

        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/exit1.png"))); // NOI18N
        jButtonClose.setBorder(null);
        jButtonClose.setBorderPainted(false);
        jButtonClose.setContentAreaFilled(false);
        jButtonClose.setFocusPainted(false);
        jButtonClose.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/exit2.png"))); // NOI18N
        jButtonClose.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/exit2.png"))); // NOI18N
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 60, 50));

        jLabelCabecera.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jLabelCabecera.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCabecera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelCabecera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/barra.png"))); // NOI18N
        jLabelCabecera.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLabelCabecera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelCabeceraMouseDragged(evt);
            }
        });
        jLabelCabecera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelCabeceraMousePressed(evt);
            }
        });
        getContentPane().add(jLabelCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        jSeparatorFondo.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparatorFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 20, 800));

        jPanelAgregarPaciente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel3.setText("Nombre/s:");
        jPanelAgregarPaciente.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 120, 30));

        jLabel1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel1.setText("Celular:");
        jPanelAgregarPaciente.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 170, 30));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel4.setText("DPI:");
        jPanelAgregarPaciente.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 120, 30));

        jLabel5.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel5.setText("Apellido/s:");
        jPanelAgregarPaciente.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 120, 30));

        jLabel6.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel6.setText("Fecha Nacimiento:");
        jPanelAgregarPaciente.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 170, 30));

        jLabel7.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel7.setText("Telefono:");
        jPanelAgregarPaciente.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 170, 30));
        jPanelAgregarPaciente.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 410, 10));

        jTextFieldDPI.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jTextFieldDPI.setBorder(null);
        jPanelAgregarPaciente.add(jTextFieldDPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 75, 410, 30));
        jPanelAgregarPaciente.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, 410, 10));

        jTextFieldNombre.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jTextFieldNombre.setBorder(null);
        jPanelAgregarPaciente.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 410, -1));
        jPanelAgregarPaciente.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 410, 10));

        jTextFieldApellido.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jTextFieldApellido.setBorder(null);
        jPanelAgregarPaciente.add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 410, -1));

        jTextFieldFechanac.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jTextFieldFechanac.setBorder(null);
        jPanelAgregarPaciente.add(jTextFieldFechanac, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 410, -1));
        jPanelAgregarPaciente.add(jSeparator8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 410, 10));

        jTextFieldTel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jTextFieldTel.setBorder(null);
        jPanelAgregarPaciente.add(jTextFieldTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 410, -1));
        jPanelAgregarPaciente.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 410, 410, 10));

        jTextFieldCel.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jTextFieldCel.setBorder(null);
        jPanelAgregarPaciente.add(jTextFieldCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 410, -1));
        jPanelAgregarPaciente.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 470, 410, 10));

        jButtonSaveDataPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/add.png"))); // NOI18N
        jButtonSaveDataPatient.setBorder(null);
        jButtonSaveDataPatient.setBorderPainted(false);
        jButtonSaveDataPatient.setContentAreaFilled(false);
        jButtonSaveDataPatient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSaveDataPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveDataPatientActionPerformed(evt);
            }
        });
        jPanelAgregarPaciente.add(jButtonSaveDataPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 90, 100));

        jLabel8.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        jLabel8.setText("Formulario para agregar un nuevo Paciente");
        jPanelAgregarPaciente.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/Extra1.png"))); // NOI18N
        jPanelAgregarPaciente.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 290, 320, 440));

        jLabel10.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel10.setText("Direccion:");
        jPanelAgregarPaciente.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 170, 30));

        jTextFieldDirec.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jTextFieldDirec.setBorder(null);
        jPanelAgregarPaciente.add(jTextFieldDirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 410, -1));
        jPanelAgregarPaciente.add(jSeparator11, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 410, 10));

        getContentPane().add(jPanelAgregarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 1070, 780));

        jPanelVerPaciente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablePatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "DPI", "Nombre", "Apellido", "Edad", "Direccion", "Telefono", "Celular"
            }
        ));
        jScrollPane1.setViewportView(jTablePatient);

        jPanelVerPaciente.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 1020, 750));

        getContentPane().add(jPanelVerPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 1070, 780));

        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonAdd.setForeground(new java.awt.Color(0, 0, 0));
        jButtonAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/nuevoP1.png"))); // NOI18N
        jButtonAdd.setText("Nuevo Paciente");
        jButtonAdd.setBorder(null);
        jButtonAdd.setBorderPainted(false);
        jButtonAdd.setContentAreaFilled(false);
        jButtonAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdd.setFocusPainted(false);
        jButtonAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAdd.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/add2.png"))); // NOI18N
        jButtonAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 120));

        jButtonVer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/verP1.png"))); // NOI18N
        jButtonVer.setBorder(null);
        jButtonVer.setBorderPainted(false);
        jButtonVer.setContentAreaFilled(false);
        jButtonVer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVer.setFocusPainted(false);
        jButtonVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVerActionPerformed(evt);
            }
        });
        jPanelFondo.add(jButtonVer, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 100, 100));

        getContentPane().add(jPanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1200, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        dispose();
        MenuMain.menuVisible();
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinActionPerformed
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButtonMinActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        jPanelAgregarPaciente.setVisible(true);
        jPanelVerPaciente.setVisible(false);
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVerActionPerformed
        jPanelVerPaciente.setVisible(true);
        jPanelAgregarPaciente.setVisible(false);
        jTablePatient.setModel(administradoPaciente.seeAllPatients());

        if (modelPatient.getRowCount() > 0) {
            modelPatient.getDataVector().removeAllElements();
            revalidate();
        } else {
            System.out.println("No hay nada que borrar");
        }
    }//GEN-LAST:event_jButtonVerActionPerformed

    private void jButtonSaveDataPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveDataPatientActionPerformed
        Object[] botones = {"Aceptar", "Cancelar"};
        int opcionElegida = JOptionPane.showOptionDialog(null, " Guardar este nuevo paciente?", "Alerta", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, botones, null);
        if (opcionElegida == 0) {
            //        Connection instance;
            System.out.println("Proceder a ");
            String DPI = jTextFieldDPI.getText();
            String nombre = jTextFieldNombre.getText();
            String apellido = jTextFieldApellido.getText();
            String fechaNac = jTextFieldFechanac.getText();
            String direccion = jTextFieldDirec.getText();
            String tel = jTextFieldTel.getText();
            String cel = jTextFieldCel.getText();

            try {
                administradoPaciente.registrarPaciente(DPI, nombre, apellido, fechaNac, direccion, tel, cel);
//            instance = BDConnection.createInstance();          
            } catch (SQLException ex) {
                ex.getCause();
            }
        } else {
            System.out.println("Cancelar operacion");
        }
    }//GEN-LAST:event_jButtonSaveDataPatientActionPerformed

    private void jLabelCabeceraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCabeceraMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabelCabeceraMousePressed

    private void jLabelCabeceraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCabeceraMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jLabelCabeceraMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FramePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FramePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FramePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FramePatient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FramePatient().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonMin;
    private javax.swing.JButton jButtonSaveDataPatient;
    private javax.swing.JButton jButtonVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelCabecera;
    private javax.swing.JPanel jPanelAgregarPaciente;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelVerPaciente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JSeparator jSeparatorFondo;
    private javax.swing.JTable jTablePatient;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldCel;
    private javax.swing.JTextField jTextFieldDPI;
    private javax.swing.JTextField jTextFieldDirec;
    private javax.swing.JTextField jTextFieldFechanac;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldTel;
    // End of variables declaration//GEN-END:variables

    private void setTablePatient() {
//         private void setTablePatient(DefaultTableModel modelPatient) {
        modelPatient.addColumn("DPI");
        modelPatient.addColumn("Nombre");
        modelPatient.addColumn("Apellido");
        modelPatient.addColumn("Edad");
        modelPatient.addColumn("Direccion");
        modelPatient.addColumn("Telefono");
        modelPatient.addColumn("Celular");
        jTablePatient.setModel(modelPatient);
        jTablePatient.getColumnModel().getColumn(0).setPreferredWidth(100);
        jTablePatient.getColumnModel().getColumn(1).setPreferredWidth(50);
        jTablePatient.getColumnModel().getColumn(2).setPreferredWidth(50);
        jTablePatient.getColumnModel().getColumn(3).setPreferredWidth(5);
        jTablePatient.getColumnModel().getColumn(4).setPreferredWidth(60);
        jTablePatient.getColumnModel().getColumn(5).setPreferredWidth(20);
        jTablePatient.getColumnModel().getColumn(6).setPreferredWidth(20);
    }

    private void setPropertiesGUI() {
        this.setLocationRelativeTo(null);
        this.setBackground(new Color(0, 0, 0, 0));
        jPanelFondo.setBackground(new Color(0xEDF0F2));
        jSeparatorFondo.setBackground(Color.BLACK);
        jPanelAgregarPaciente.setVisible(false);
        jPanelAgregarPaciente.setBackground(Color.WHITE);
        jPanelVerPaciente.setVisible(false);
        jPanelVerPaciente.setBackground(Color.WHITE);
    }
}
