/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pckgPaciente;

import Iinterfazes.iControlUI;
import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.IOException;
import java.sql.SQLException;
import java.text.DateFormatSymbols;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.UIManager.LookAndFeelInfo;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.border.Border;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import org.netbeans.lib.awtextra.AbsoluteConstraints;
import pckgMenu.MenuMain;

/**
 * @author allecc
 */
public class FramePatient extends javax.swing.JFrame implements iControlUI {

    private int x, y;
    AdminPatient adminPaciente;
    public int year = Calendar.getInstance().get(Calendar.YEAR);
    private JLabel jLblButton1;
    private JLabel jLblButton2;
    private JLabel jLblButton3;
    private Font OpenSans;
    private Font OpenSansItalic;

    public FramePatient() {
        initComponents();
        setPropertiesGUI();
        adminPaciente = new AdminPatient();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
//    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        toggleGroup = new javax.swing.ButtonGroup();
        jButtonMin = new javax.swing.JButton();
        jButtonClose = new javax.swing.JButton();
        jLabelBarraCabecera = new javax.swing.JLabel();
        jSeparatorFondo = new javax.swing.JSeparator();
        jPanelAgregarPaciente = new javax.swing.JPanel();
        jTextFieldNombre = new RoundJTextField(10);
        jTextFieldApellido = new RoundJTextField(10);
        jTextFieldDirec = new RoundJTextField(10);
        jFtdTxtANIO = new RoundJFTextField();
        jFtdTxtCEL = new RoundJFTextField();
        jFtdTxtTEL = new RoundJFTextField();
        jComboDia = new javax.swing.JComboBox<>();
        jComboMes = new javax.swing.JComboBox<>();
        jButtonSaveDataPatient = new javax.swing.JButton();
        jLabelNombre = new javax.swing.JLabel();
        jLabelCel = new javax.swing.JLabel();
        jLabelApellido = new javax.swing.JLabel();
        jLabelFechaNac = new javax.swing.JLabel();
        jLabelTel = new javax.swing.JLabel();
        labelTitutloAgregar = new javax.swing.JLabel();
        jLabelDirecc = new javax.swing.JLabel();
        jLabelNotificacion = new javax.swing.JLabel();
        jLblNotiStatusDPI = new javax.swing.JLabel();
        jLblNotiStatusCEL = new javax.swing.JLabel();
        jLblNotiStatusTEL = new javax.swing.JLabel();
        jFtdTxtDPI = new RoundJFTextField();
        jLabelIMG1 = new javax.swing.JLabel();
        jLabelIMG2 = new javax.swing.JLabel();
        jLabelIMG3 = new javax.swing.JLabel();
        jLabeiCO1 = new javax.swing.JLabel();
        jLabelDPI = new javax.swing.JLabel();
        jLblNotiDPI = new javax.swing.JLabel();
        jLblNotiTEL = new javax.swing.JLabel();
        jLblNotiCEL = new javax.swing.JLabel();
        jLblNotiNME = new javax.swing.JLabel();
        jLblNotiLNME = new javax.swing.JLabel();
        jLblNotiADRS = new javax.swing.JLabel();
        jLblNotiStatusNME = new javax.swing.JLabel();
        jLblNotiStatusLNME = new javax.swing.JLabel();
        jLblNotiStatusADRS = new javax.swing.JLabel();
        jLblNotiStatusFechaNac = new javax.swing.JLabel();
        jLblNotiFechaNac = new javax.swing.JLabel();
        jPanelVerPaciente = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePatient = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jTextFieldSearching = new javax.swing.JTextField();
        jLabelBuscar = new javax.swing.JLabel();
        labelTitutloVisualizar = new javax.swing.JLabel();
        jPanelFondo = new javax.swing.JPanel();
        toggleButtonVisualizar = new javax.swing.JToggleButton();
        toggleButtonNuevo = new javax.swing.JToggleButton();
        jBttnExitToMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonMin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/min1.png"))); // NOI18N
        jButtonMin.setBorder(null);
        jButtonMin.setBorderPainted(false);
        jButtonMin.setContentAreaFilled(false);
        jButtonMin.setFocusPainted(false);
        jButtonMin.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/min2.png"))); // NOI18N
        jButtonMin.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/min2.png"))); // NOI18N
        jButtonMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, 50, 50));

        jButtonClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/exit1.png"))); // NOI18N
        jButtonClose.setBorder(null);
        jButtonClose.setBorderPainted(false);
        jButtonClose.setContentAreaFilled(false);
        jButtonClose.setFocusPainted(false);
        jButtonClose.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/exit2.png"))); // NOI18N
        jButtonClose.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/exit2.png"))); // NOI18N
        jButtonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCloseActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 0, 60, 50));

        jLabelBarraCabecera.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 36)); // NOI18N
        jLabelBarraCabecera.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBarraCabecera.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBarraCabecera.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/barra.png"))); // NOI18N
        jLabelBarraCabecera.setCursor(new java.awt.Cursor(java.awt.Cursor.MOVE_CURSOR));
        jLabelBarraCabecera.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabelBarraCabeceraMouseDragged(evt);
            }
        });
        jLabelBarraCabecera.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabelBarraCabeceraMousePressed(evt);
            }
        });
        getContentPane().add(jLabelBarraCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 50));

        jSeparatorFondo.setBackground(new java.awt.Color(0, 0, 0));
        jSeparatorFondo.setForeground(new java.awt.Color(0, 0, 0));
        jSeparatorFondo.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparatorFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(129, 20, 10, 800));

        jPanelAgregarPaciente.setFocusable(false);
        jPanelAgregarPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanelAgregarPacienteMouseClicked(evt);
            }
        });
        jPanelAgregarPaciente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldNombre.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNombre.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldNombre.setBorder(null);
        jTextFieldNombre.setMinimumSize(new java.awt.Dimension(400, 35));
        jTextFieldNombre.setPreferredSize(new java.awt.Dimension(400, 35));
        jTextFieldNombre.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldNombreFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldNombreFocusLost(evt);
            }
        });
        jPanelAgregarPaciente.add(jTextFieldNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 190, 400, 35));

        jTextFieldApellido.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldApellido.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldApellido.setBorder(null);
        jTextFieldApellido.setMinimumSize(new java.awt.Dimension(400, 35));
        jTextFieldApellido.setPreferredSize(new java.awt.Dimension(400, 35));
        jTextFieldApellido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldApellidoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldApellidoFocusLost(evt);
            }
        });
        jPanelAgregarPaciente.add(jTextFieldApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 275, 400, 35));

        jTextFieldDirec.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldDirec.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldDirec.setBorder(null);
        jTextFieldDirec.setMinimumSize(new java.awt.Dimension(400, 35));
        jTextFieldDirec.setPreferredSize(new java.awt.Dimension(400, 35));
        jTextFieldDirec.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextFieldDirecFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextFieldDirecFocusLost(evt);
            }
        });
        jPanelAgregarPaciente.add(jTextFieldDirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 360, 400, 35));

        jFtdTxtANIO.setBorder(null);
        try {
            jFtdTxtANIO.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFtdTxtANIO.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFtdTxtANIO.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jFtdTxtANIO.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFtdTxtANIOFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFtdTxtANIOFocusLost(evt);
            }
        });
        jPanelAgregarPaciente.add(jFtdTxtANIO, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 615, 95, 35));

        jFtdTxtCEL.setBorder(null);
        try {
            jFtdTxtCEL.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFtdTxtCEL.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFtdTxtCEL.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jFtdTxtCEL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFtdTxtCELFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFtdTxtCELFocusLost(evt);
            }
        });
        jPanelAgregarPaciente.add(jFtdTxtCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 530, 400, 35));

        jFtdTxtTEL.setBorder(null);
        try {
            jFtdTxtTEL.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFtdTxtTEL.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFtdTxtTEL.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jFtdTxtTEL.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFtdTxtTELFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFtdTxtTELFocusLost(evt);
            }
        });
        jPanelAgregarPaciente.add(jFtdTxtTEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 445, 400, 35));

        jComboDia.setAlignmentX(0.0F);
        jComboDia.setAlignmentY(0.0F);
        jComboDia.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboDia.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboDiaFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboDiaFocusLost(evt);
            }
        });
        jPanelAgregarPaciente.add(jComboDia, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 615, 85, 35));

        jComboMes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboMes.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jComboMesFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jComboMesFocusLost(evt);
            }
        });
        jPanelAgregarPaciente.add(jComboMes, new org.netbeans.lib.awtextra.AbsoluteConstraints(425, 615, 160, 35));

        jButtonSaveDataPatient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/button (1).png"))); // NOI18N
        jButtonSaveDataPatient.setBorder(null);
        jButtonSaveDataPatient.setBorderPainted(false);
        jButtonSaveDataPatient.setContentAreaFilled(false);
        jButtonSaveDataPatient.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSaveDataPatient.setFocusPainted(false);
        jButtonSaveDataPatient.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/button (2).png"))); // NOI18N
        jButtonSaveDataPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveDataPatientActionPerformed(evt);
            }
        });
        jPanelAgregarPaciente.add(jButtonSaveDataPatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 20, 140, 45));

        jLabelNombre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/Nombres.png"))); // NOI18N
        jPanelAgregarPaciente.add(jLabelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 185, 178, 45));

        jLabelCel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/Cel.png"))); // NOI18N
        jPanelAgregarPaciente.add(jLabelCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 525, 153, 45));

        jLabelApellido.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/Apellido.png"))); // NOI18N
        jPanelAgregarPaciente.add(jLabelApellido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 182, 45));

        jLabelFechaNac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/FechaNac.png"))); // NOI18N
        jPanelAgregarPaciente.add(jLabelFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 610, 200, 45));

        jLabelTel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/Tel.png"))); // NOI18N
        jPanelAgregarPaciente.add(jLabelTel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, 176, 45));

        labelTitutloAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/Titulo1.png"))); // NOI18N
        jPanelAgregarPaciente.add(labelTitutloAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 400, 45));

        jLabelDirecc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/Direccion.png"))); // NOI18N
        jPanelAgregarPaciente.add(jLabelDirecc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 355, 186, 45));

        jLabelNotificacion.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jPanelAgregarPaciente.add(jLabelNotificacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 740, 350, 40));

        jLblNotiStatusDPI.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblNotiStatusDPI.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelAgregarPaciente.add(jLblNotiStatusDPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 95, 55, 55));

        jPanelAgregarPaciente.add(jLblNotiStatusCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 520, 55, 55));

        jLblNotiStatusTEL.setToolTipText("");
        jPanelAgregarPaciente.add(jLblNotiStatusTEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 435, 55, 55));

        jFtdTxtDPI.setBorder(null);
        try {
            jFtdTxtDPI.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#### ##### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFtdTxtDPI.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jFtdTxtDPI.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jFtdTxtDPI.setFocusLostBehavior(javax.swing.JFormattedTextField.PERSIST);
        jFtdTxtDPI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFtdTxtDPIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFtdTxtDPIFocusLost(evt);
            }
        });
        jPanelAgregarPaciente.add(jFtdTxtDPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 105, 400, 35));

        jLabelIMG1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/Vector.png"))); // NOI18N
        jPanelAgregarPaciente.add(jLabelIMG1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 0, 270, 540));

        jLabelIMG2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/Vector2.png"))); // NOI18N
        jPanelAgregarPaciente.add(jLabelIMG2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 580, 80));

        jLabelIMG3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelIMG3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/cepilloR.png"))); // NOI18N
        jPanelAgregarPaciente.add(jLabelIMG3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 580, 170, 210));

        jLabeiCO1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/ico (4).png"))); // NOI18N
        jPanelAgregarPaciente.add(jLabeiCO1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 25, 25));

        jLabelDPI.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/DPI.png"))); // NOI18N
        jPanelAgregarPaciente.add(jLabelDPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 57, 45));

        jLblNotiDPI.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jPanelAgregarPaciente.add(jLblNotiDPI, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 145, 150, 20));

        jLblNotiTEL.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jPanelAgregarPaciente.add(jLblNotiTEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 485, 150, 20));

        jLblNotiCEL.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jPanelAgregarPaciente.add(jLblNotiCEL, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 570, 150, 20));

        jLblNotiNME.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jPanelAgregarPaciente.add(jLblNotiNME, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 230, 150, 20));

        jLblNotiLNME.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jPanelAgregarPaciente.add(jLblNotiLNME, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 315, 150, 20));

        jLblNotiADRS.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jPanelAgregarPaciente.add(jLblNotiADRS, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 400, 150, 20));

        jLblNotiStatusNME.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblNotiStatusNME.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelAgregarPaciente.add(jLblNotiStatusNME, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, 55, 55));

        jLblNotiStatusLNME.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblNotiStatusLNME.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelAgregarPaciente.add(jLblNotiStatusLNME, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 265, 55, 55));

        jLblNotiStatusADRS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblNotiStatusADRS.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanelAgregarPaciente.add(jLblNotiStatusADRS, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 350, 55, 55));

        jPanelAgregarPaciente.add(jLblNotiStatusFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 605, 55, 55));

        jLblNotiFechaNac.setFont(new java.awt.Font("Calibri", 0, 15)); // NOI18N
        jPanelAgregarPaciente.add(jLblNotiFechaNac, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 655, 150, 20));

        getContentPane().add(jPanelAgregarPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 1070, 780));

        jPanelVerPaciente.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTablePatient.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jTablePatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "DPI", "Nombre", "Apellido", "Edad", "Direccion", "Telefono", "Celular"
            }
        ));
        jTablePatient.setCellSelectionEnabled(true);
        jTablePatient.setFocusable(false);
        jTablePatient.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jTablePatient.setShowGrid(false);
        jTablePatient.setShowVerticalLines(true);
        jTablePatient.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTablePatient);

        jPanelVerPaciente.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 1030, 690));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jPanelVerPaciente.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 55, 410, 5));

        jTextFieldSearching.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextFieldSearchingMouseClicked(evt);
            }
        });
        jTextFieldSearching.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldSearchingKeyReleased(evt);
            }
        });
        jPanelVerPaciente.add(jTextFieldSearching, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 410, 30));

        jLabelBuscar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/search.png"))); // NOI18N
        jLabelBuscar.setPreferredSize(new java.awt.Dimension(46, 46));
        jPanelVerPaciente.add(jLabelBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1001, 17, 50, 45));

        labelTitutloVisualizar.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 36)); // NOI18N
        labelTitutloVisualizar.setText("Listado pacientes");
        jPanelVerPaciente.add(labelTitutloVisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        getContentPane().add(jPanelVerPaciente, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 1070, 780));

        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        toggleGroup.add(toggleButtonVisualizar);
        toggleButtonVisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/seeP1.png"))); // NOI18N
        toggleButtonVisualizar.setBorder(null);
        toggleButtonVisualizar.setBorderPainted(false);
        toggleButtonVisualizar.setContentAreaFilled(false);
        toggleButtonVisualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toggleButtonVisualizar.setFocusPainted(false);
        toggleButtonVisualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toggleButtonVisualizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/seeP2.png"))); // NOI18N
        toggleButtonVisualizar.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/seeP3.png"))); // NOI18N
        toggleButtonVisualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toggleButtonVisualizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                toggleButtonVisualizarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                toggleButtonVisualizarMouseExited(evt);
            }
        });
        toggleButtonVisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonVisualizarActionPerformed(evt);
            }
        });
        jPanelFondo.add(toggleButtonVisualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 130, 100));

        toggleGroup.add(toggleButtonNuevo);
        toggleButtonNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/newP1.png"))); // NOI18N
        toggleButtonNuevo.setBorder(null);
        toggleButtonNuevo.setBorderPainted(false);
        toggleButtonNuevo.setContentAreaFilled(false);
        toggleButtonNuevo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        toggleButtonNuevo.setFocusPainted(false);
        toggleButtonNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toggleButtonNuevo.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/newP2.png"))); // NOI18N
        toggleButtonNuevo.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/newP3.png"))); // NOI18N
        toggleButtonNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        toggleButtonNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                toggleButtonNuevoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                toggleButtonNuevoMouseExited(evt);
            }
        });
        toggleButtonNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleButtonNuevoActionPerformed(evt);
            }
        });
        jPanelFondo.add(toggleButtonNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 130, 100));

        jBttnExitToMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/exitToMenu1.png"))); // NOI18N
        jBttnExitToMenu.setBorder(null);
        jBttnExitToMenu.setBorderPainted(false);
        jBttnExitToMenu.setContentAreaFilled(false);
        jBttnExitToMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBttnExitToMenu.setFocusable(false);
        jBttnExitToMenu.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/pckgPaciente/imgs/exitToMenu2.png"))); // NOI18N
        jBttnExitToMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jBttnExitToMenuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jBttnExitToMenuMouseExited(evt);
            }
        });
        jBttnExitToMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBttnExitToMenuActionPerformed(evt);
            }
        });
        jPanelFondo.add(jBttnExitToMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 680, 130, 100));

        getContentPane().add(jPanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1200, 780));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCloseActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButtonCloseActionPerformed

    private void jButtonMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinActionPerformed
        this.setState(ICONIFIED);
    }//GEN-LAST:event_jButtonMinActionPerformed

    private void jLabelBarraCabeceraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBarraCabeceraMousePressed
        x = evt.getX();
        y = evt.getY();
    }//GEN-LAST:event_jLabelBarraCabeceraMousePressed

    private void jLabelBarraCabeceraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelBarraCabeceraMouseDragged
        this.setLocation(this.getLocation().x + evt.getX() - x, this.getLocation().y + evt.getY() - y);
    }//GEN-LAST:event_jLabelBarraCabeceraMouseDragged

    private void toggleButtonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonNuevoActionPerformed
        jPanelAgregarPaciente.setVisible(true);
        jPanelAgregarPaciente.requestFocusInWindow();
        jPanelVerPaciente.setVisible(false);
        setInicialComponents();
    }//GEN-LAST:event_toggleButtonNuevoActionPerformed

    private void toggleButtonVisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleButtonVisualizarActionPerformed
        jPanelVerPaciente.setVisible(true);
        jPanelAgregarPaciente.setVisible(false);
        jTablePatient.setModel(adminPaciente.seeAllPatients());
        jTablePatient.setAutoCreateRowSorter(true);
    }//GEN-LAST:event_toggleButtonVisualizarActionPerformed

    private void jTextFieldSearchingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextFieldSearchingMouseClicked
        Font font = new Font("Segoe UI Semilight", Font.PLAIN, 18);
        jTextFieldSearching.setText("");
        jTextFieldSearching.setForeground(Color.black);
        jTextFieldSearching.setFont(font);
    }//GEN-LAST:event_jTextFieldSearchingMouseClicked

    private void jTextFieldSearchingKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldSearchingKeyReleased
        TableRowSorter<TableModel> tableFilter = new TableRowSorter<TableModel>(jTablePatient.getModel());
        jTablePatient.setRowSorter(tableFilter);
        tableFilter.setRowFilter(RowFilter.regexFilter(jTextFieldSearching.getText()));
    }//GEN-LAST:event_jTextFieldSearchingKeyReleased

    private void jButtonSaveDataPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveDataPatientActionPerformed
        Object[] botones = {"Aceptar", "Cancelar"};
        int opcionElegida = JOptionPane.showOptionDialog(null, " Guardar este nuevo paciente?", "Alerta", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, null, botones, null);
        if (opcionElegida == 0) {
            if (verificarIcons(0) == true) {
                notiOKNT(0);
            } else {
                if (verificarIcons(1) == true) {
                    System.out.println("SI");
                    String DPI = jFtdTxtDPI.getText().replaceAll("\\s+", "");
                    String nombre = jTextFieldNombre.getText();
                    String apellido = jTextFieldApellido.getText();
                    String[] fechaNac = new String[3];
                    fechaNac[0] = jFtdTxtANIO.getText();
                    fechaNac[1] = String.valueOf(jComboMes.getSelectedItem());
                    fechaNac[2] = String.valueOf(jComboDia.getSelectedItem());
                    String direccion = jTextFieldDirec.getText();
                    String tel = jFtdTxtTEL.getText().replaceAll("\\s+", "");
                    String cel = jFtdTxtCEL.getText().replaceAll("\\s+", "");
                    try {
                        boolean status = adminPaciente.registrarPaciente(DPI, nombre, apellido, fechaNac, direccion, tel, cel);
                        if (status == true) {
                            notiOKNT(1);
                            setInicialComponents();
                        } else {
                            System.out.println("Algo salio mal en SQL");
                        }
                    } catch (SQLException ex) {
                        ex.getMessage();
                    }
                } else {
                    notiOKNT(0);
                }
            }
        } else {
            System.out.println("Cancelar operacion");
        }
    }//GEN-LAST:event_jButtonSaveDataPatientActionPerformed

    private void jFtdTxtDPIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFtdTxtDPIFocusGained
        if (jFtdTxtDPI.getText().equals("9999 99999 9999")) {
            jFtdTxtDPI.setText("");
            jFtdTxtDPI.setFont(OpenSans);
            jFtdTxtDPI.setForeground(Color.black);
        } else {
            reAdjustCaret(1);
            jLblNotiStatusDPI.setIcon(null);
            jLblNotiDPI.setText("");
            jFtdTxtDPI.setBackground(Color.decode("#CEF8E9"));
        }
    }//GEN-LAST:event_jFtdTxtDPIFocusGained

    private void jFtdTxtDPIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFtdTxtDPIFocusLost
        if (jFtdTxtDPI.getText().replaceAll("\\s+", "").length() == 13) {
            jFtdTxtDPI.setBackground(Color.decode("#19DEA3"));
            jLblNotiStatusDPI.setIcon(null);
            jLblNotiStatusDPI.setIcon(new ImageIcon(getClass().getResource("/pckgPaciente/imgs/okICO.png")));
            jLblNotiDPI.setText("");

        } else {
            jLblNotiStatusDPI.setIcon(null);
            jLblNotiStatusDPI.setIcon(new ImageIcon(getClass().getResource("/pckgPaciente/imgs/notokICO.png")));
            jFtdTxtDPI.setBackground(Color.decode("#FFA6A6"));
            jLblNotiDPI.setText("Campo incompleto");
        }

    }//GEN-LAST:event_jFtdTxtDPIFocusLost

    private void jFtdTxtTELFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFtdTxtTELFocusGained
        if (jFtdTxtTEL.getText().equals("7777 7777")) {
            jFtdTxtTEL.setText("");
            jFtdTxtTEL.setFont(OpenSans);
            jFtdTxtTEL.setForeground(Color.black);
        } else {
            reAdjustCaret(2);
            jLblNotiStatusTEL.setIcon(null);
            jLblNotiTEL.setText("");
            jFtdTxtTEL.setBackground(Color.decode("#CEF8E9"));
        }
    }//GEN-LAST:event_jFtdTxtTELFocusGained

    private void jFtdTxtTELFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFtdTxtTELFocusLost
        if (jFtdTxtTEL.getText().replaceAll("\\s+", "").length() == 8) {
            jFtdTxtTEL.setBackground(Color.decode("#19DEA3"));
            jLblNotiStatusTEL.setIcon(null);
            jLblNotiStatusTEL.setIcon(new ImageIcon(getClass().getResource("/pckgPaciente/imgs/okICO.png")));
            jLblNotiTEL.setText("");
        } else {
            jLblNotiStatusTEL.setIcon(null);
            jLblNotiStatusTEL.setIcon(new ImageIcon(getClass().getResource("/pckgPaciente/imgs/notokICO.png")));
            jFtdTxtTEL.setBackground(Color.decode("#FFA6A6"));
            jLblNotiTEL.setText("Campo incompleto");
        }
    }//GEN-LAST:event_jFtdTxtTELFocusLost

    private void jFtdTxtCELFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFtdTxtCELFocusGained
        if (jFtdTxtCEL.getText().equals("5555 5555")) {
            jFtdTxtCEL.setText("");
            jFtdTxtCEL.setFont(OpenSans);
            jFtdTxtCEL.setForeground(Color.black);
        } else {
            reAdjustCaret(3);
            jLblNotiStatusCEL.setIcon(null);
            jLblNotiCEL.setText("");
            jFtdTxtCEL.setBackground(Color.decode("#CEF8E9"));
        }
    }//GEN-LAST:event_jFtdTxtCELFocusGained

    private void jFtdTxtCELFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFtdTxtCELFocusLost
        if (jFtdTxtCEL.getText().replaceAll("\\s+", "").length() == 8) {
            jFtdTxtCEL.setBackground(Color.decode("#19DEA3"));
            jLblNotiStatusCEL.setIcon(null);
            jLblNotiStatusCEL.setIcon(new ImageIcon(getClass().getResource("/pckgPaciente/imgs/okICO.png")));
            jLblNotiCEL.setText("");
        } else {
            jLblNotiStatusCEL.setIcon(null);
            jLblNotiStatusCEL.setIcon(new ImageIcon(getClass().getResource("/pckgPaciente/imgs/notokICO.png")));
            jFtdTxtCEL.setBackground(Color.decode("#FFA6A6"));
            jLblNotiCEL.setText("Campo incompleto");
        }
    }//GEN-LAST:event_jFtdTxtCELFocusLost

    private void jTextFieldNombreFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreFocusGained
        if (jTextFieldNombre.getText().equals("Escribir Nombres...")) {
            jTextFieldNombre.setText("");
            jTextFieldNombre.setFont(OpenSans);
            jTextFieldNombre.setForeground(Color.black);
        } else {
            jLblNotiStatusNME.setIcon(null);
            jLblNotiNME.setText("");
            jTextFieldNombre.setBackground(Color.decode("#CEF8E9"));
        }
    }//GEN-LAST:event_jTextFieldNombreFocusGained

    private void jTextFieldNombreFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldNombreFocusLost
        if (jTextFieldNombre.getText().length() >= 2) {
            jTextFieldNombre.setBackground(Color.decode("#19DEA3"));
            jLblNotiStatusNME.setIcon(null);
            jLblNotiStatusNME.setIcon(new ImageIcon(getClass().getResource("/pckgPaciente/imgs/okICO.png")));
            jLblNotiNME.setText("");
        } else {
            jLblNotiStatusNME.setIcon(null);
            jLblNotiStatusNME.setIcon(new ImageIcon(getClass().getResource("/pckgPaciente/imgs/notokICO.png")));
            jTextFieldNombre.setBackground(Color.decode("#FFA6A6"));
            jLblNotiNME.setText("Campo incompleto");
        }
    }//GEN-LAST:event_jTextFieldNombreFocusLost

    private void jTextFieldApellidoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldApellidoFocusGained
        if (jTextFieldApellido.getText().equals("Escribir Apellidos...")) {
            jTextFieldApellido.setText("");
            jTextFieldApellido.setFont(OpenSans);
            jTextFieldApellido.setForeground(Color.black);
        } else {
            jLblNotiStatusLNME.setIcon(null);
            jLblNotiLNME.setText("");
            jTextFieldApellido.setBackground(Color.decode("#CEF8E9"));
        }
    }//GEN-LAST:event_jTextFieldApellidoFocusGained

    private void jTextFieldApellidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldApellidoFocusLost
        if (jTextFieldApellido.getText().length() >= 2) {
            jTextFieldApellido.setBackground(Color.decode("#19DEA3"));
            jLblNotiStatusLNME.setIcon(null);
            jLblNotiStatusLNME.setIcon(new ImageIcon(getClass().getResource("/pckgPaciente/imgs/okICO.png")));
            jLblNotiLNME.setText("");
        } else {
            jLblNotiStatusLNME.setIcon(null);
            jLblNotiStatusLNME.setIcon(new ImageIcon(getClass().getResource("/pckgPaciente/imgs/notokICO.png")));
            jTextFieldApellido.setBackground(Color.decode("#FFA6A6"));
            jLblNotiLNME.setText("Campo incompleto");
        }
    }//GEN-LAST:event_jTextFieldApellidoFocusLost

    private void jTextFieldDirecFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDirecFocusGained
        if (jTextFieldDirec.getText().equals("Escribir Direccion...")) {
            jTextFieldDirec.setText("");
            jTextFieldDirec.setFont(OpenSans);
            jTextFieldDirec.setForeground(Color.black);
        } else {
            jLblNotiStatusADRS.setIcon(null);
            jLblNotiADRS.setText("");
            jTextFieldDirec.setBackground(Color.decode("#CEF8E9"));
        }
    }//GEN-LAST:event_jTextFieldDirecFocusGained

    private void jTextFieldDirecFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextFieldDirecFocusLost
        if (jTextFieldDirec.getText().length() >= 2) {
            jTextFieldDirec.setBackground(Color.decode("#19DEA3"));
            jLblNotiStatusADRS.setIcon(null);
            jLblNotiStatusADRS.setIcon(new ImageIcon(getClass().getResource("/pckgPaciente/imgs/okICO.png")));
            jLblNotiADRS.setText("");
        } else {
            jLblNotiStatusADRS.setIcon(null);
            jLblNotiStatusADRS.setIcon(new ImageIcon(getClass().getResource("/pckgPaciente/imgs/notokICO.png")));
            jTextFieldDirec.setBackground(Color.decode("#FFA6A6"));
            jLblNotiADRS.setText("Campo incompleto");
        }
    }//GEN-LAST:event_jTextFieldDirecFocusLost

    private void jPanelAgregarPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanelAgregarPacienteMouseClicked
        jLabelIMG2.requestFocus();
    }//GEN-LAST:event_jPanelAgregarPacienteMouseClicked

    private void toggleButtonNuevoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleButtonNuevoMouseEntered
        ImageIcon imgicon = new ImageIcon(getClass().getResource("/pckgPaciente/imgs/tooltipB1ICO.png"));
        jLblButton1.setIcon(imgicon);
    }//GEN-LAST:event_toggleButtonNuevoMouseEntered

    private void toggleButtonNuevoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleButtonNuevoMouseExited
        this.jLblButton1.setIcon(null);
    }//GEN-LAST:event_toggleButtonNuevoMouseExited

    private void toggleButtonVisualizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleButtonVisualizarMouseEntered
        ImageIcon imgicon = new ImageIcon(getClass().getResource("/pckgPaciente/imgs/tooltipB2ICO.png"));
        jLblButton2.setIcon(imgicon);
    }//GEN-LAST:event_toggleButtonVisualizarMouseEntered

    private void toggleButtonVisualizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleButtonVisualizarMouseExited
        this.jLblButton2.setIcon(null);
    }//GEN-LAST:event_toggleButtonVisualizarMouseExited

    private void jBttnExitToMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBttnExitToMenuActionPerformed
        dispose();
        MenuMain.menuVisible();
    }//GEN-LAST:event_jBttnExitToMenuActionPerformed

    private void jBttnExitToMenuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBttnExitToMenuMouseEntered
        ImageIcon imgicon = new ImageIcon(getClass().getResource("/pckgPaciente/imgs/tooltipB3CO.png"));
        jLblButton3.setIcon(imgicon);
    }//GEN-LAST:event_jBttnExitToMenuMouseEntered

    private void jBttnExitToMenuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBttnExitToMenuMouseExited
        this.jLblButton3.setIcon(null);
    }//GEN-LAST:event_jBttnExitToMenuMouseExited

    private void jFtdTxtANIOFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFtdTxtANIOFocusGained
        if (jFtdTxtANIO.getText().equals(String.valueOf(year))) {
            jFtdTxtANIO.setText("");
            jFtdTxtANIO.setFont(OpenSans);
            jFtdTxtANIO.setForeground(Color.black);
        } else {
            jLblNotiStatusFechaNac.setIcon(null);
            jLblNotiFechaNac.setText("");
            jFtdTxtANIO.setBackground(Color.decode("#CEF8E9"));
            reAdjustCaret(4);
        }
    }//GEN-LAST:event_jFtdTxtANIOFocusGained

    private void jFtdTxtANIOFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFtdTxtANIOFocusLost

        if (jFtdTxtANIO.getText().replaceAll("\\s+", "").length() == 0) {
            jLblNotiStatusFechaNac.setIcon(null);
            jLblNotiStatusFechaNac.setIcon(new ImageIcon(getClass().getResource("/pckgPaciente/imgs/notokICO.png")));
            jFtdTxtANIO.setBackground(Color.decode("#FFA6A6"));
            jLblNotiFechaNac.setText("Campo incompleto");
        } else {
            int yearLabel = Integer.parseInt(jFtdTxtANIO.getText().replaceAll("\\s+", ""));
            if (yearLabel >= year - 100 && yearLabel <= year) {
                jFtdTxtANIO.setBackground(Color.decode("#19DEA3"));
                jLblNotiStatusFechaNac.setIcon(null);
                jLblNotiStatusFechaNac.setIcon(new ImageIcon(getClass().getResource("/pckgPaciente/imgs/okICO.png")));
                jLblNotiFechaNac.setText("");
            } else {
                jLblNotiStatusFechaNac.setIcon(null);
                jLblNotiStatusFechaNac.setIcon(new ImageIcon(getClass().getResource("/pckgPaciente/imgs/notokICO.png")));
                jFtdTxtANIO.setBackground(Color.decode("#FFA6A6"));
                jLblNotiFechaNac.setText("Año incorrecto");
            }
        }
    }//GEN-LAST:event_jFtdTxtANIOFocusLost

    private void jComboDiaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboDiaFocusGained
        if (jComboDia.getItemAt(0).equals("Dia")) {
            jComboDia.removeItemAt(0);
            jComboDia.setSelectedIndex(-1);
            jComboDia.setFont(OpenSans);
            jComboDia.setForeground(Color.BLACK);
        } else {
            jComboDia.setUI(new ComboCustomUI(0));
            jComboDia.showPopup();
        }
    }//GEN-LAST:event_jComboDiaFocusGained

    private void jComboDiaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboDiaFocusLost
        if (jComboDia.getSelectedItem() == null) {
            jComboDia.setUI(new ComboCustomUI(2));
            jLblNotiStatusFechaNac.setIcon(null);
            jLblNotiStatusFechaNac.setIcon(new ImageIcon(getClass().getResource("/pckgPaciente/imgs/notokICO.png")));
            jLblNotiFechaNac.setText("Campo incompleto");
        } else {
            jComboDia.setUI(new ComboCustomUI(1));
            jLblNotiStatusFechaNac.setIcon(null);
            jLblNotiFechaNac.setText("");
        }
    }//GEN-LAST:event_jComboDiaFocusLost

    private void jComboMesFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboMesFocusGained
        if (jComboMes.getItemAt(0).equals("Mes")) {
            jComboMes.removeItemAt(0);
            jComboMes.setSelectedIndex(-1);
            jComboMes.setFont(OpenSans);
            jComboMes.setForeground(Color.BLACK);
        } else {
            jComboMes.setUI(new ComboCustomUI(0));
            jComboMes.showPopup();
        }
    }//GEN-LAST:event_jComboMesFocusGained

    private void jComboMesFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jComboMesFocusLost
        if (jComboMes.getSelectedItem() == null) {
            jComboMes.setUI(new ComboCustomUI(2));
            jLblNotiStatusFechaNac.setIcon(null);
            jLblNotiStatusFechaNac.setIcon(new ImageIcon(getClass().getResource("/pckgPaciente/imgs/notokICO.png")));
            jLblNotiFechaNac.setText("Campo incompleto");
        } else {
            jComboMes.setUI(new ComboCustomUI(1));
            jLblNotiStatusFechaNac.setIcon(null);
            jLblNotiFechaNac.setText("");
        }
    }//GEN-LAST:event_jComboMesFocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBttnExitToMenu;
    private javax.swing.JButton jButtonClose;
    private javax.swing.JButton jButtonMin;
    private javax.swing.JButton jButtonSaveDataPatient;
    private javax.swing.JComboBox<String> jComboDia;
    private javax.swing.JComboBox<String> jComboMes;
    private javax.swing.JFormattedTextField jFtdTxtANIO;
    private javax.swing.JFormattedTextField jFtdTxtCEL;
    private javax.swing.JFormattedTextField jFtdTxtDPI;
    private javax.swing.JFormattedTextField jFtdTxtTEL;
    private javax.swing.JLabel jLabeiCO1;
    private javax.swing.JLabel jLabelApellido;
    private javax.swing.JLabel jLabelBarraCabecera;
    private javax.swing.JLabel jLabelBuscar;
    private javax.swing.JLabel jLabelCel;
    private javax.swing.JLabel jLabelDPI;
    private javax.swing.JLabel jLabelDirecc;
    private javax.swing.JLabel jLabelFechaNac;
    private javax.swing.JLabel jLabelIMG1;
    private javax.swing.JLabel jLabelIMG2;
    private javax.swing.JLabel jLabelIMG3;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNotificacion;
    private javax.swing.JLabel jLabelTel;
    private javax.swing.JLabel jLblNotiADRS;
    private javax.swing.JLabel jLblNotiCEL;
    private javax.swing.JLabel jLblNotiDPI;
    private javax.swing.JLabel jLblNotiFechaNac;
    private javax.swing.JLabel jLblNotiLNME;
    private javax.swing.JLabel jLblNotiNME;
    private javax.swing.JLabel jLblNotiStatusADRS;
    private javax.swing.JLabel jLblNotiStatusCEL;
    private javax.swing.JLabel jLblNotiStatusDPI;
    private javax.swing.JLabel jLblNotiStatusFechaNac;
    private javax.swing.JLabel jLblNotiStatusLNME;
    private javax.swing.JLabel jLblNotiStatusNME;
    private javax.swing.JLabel jLblNotiStatusTEL;
    private javax.swing.JLabel jLblNotiTEL;
    private javax.swing.JPanel jPanelAgregarPaciente;
    private javax.swing.JPanel jPanelFondo;
    private javax.swing.JPanel jPanelVerPaciente;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparatorFondo;
    private javax.swing.JTable jTablePatient;
    private javax.swing.JTextField jTextFieldApellido;
    private javax.swing.JTextField jTextFieldDirec;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldSearching;
    private javax.swing.JLabel labelTitutloAgregar;
    private javax.swing.JLabel labelTitutloVisualizar;
    private javax.swing.JToggleButton toggleButtonNuevo;
    private javax.swing.JToggleButton toggleButtonVisualizar;
    private javax.swing.ButtonGroup toggleGroup;
    // End of variables declaration//GEN-END:variables

    @Override
    public void setPropertiesGUI() {
        try {
            this.OpenSans = Font.createFont(Font.TRUETYPE_FONT,
                    getClass().getResourceAsStream("/Fonts/OpenSans-Regular.ttf"));
            this.OpenSans = OpenSans.deriveFont(Font.PLAIN, 23f);
            this.OpenSansItalic = Font.createFont(Font.TRUETYPE_FONT,
                    getClass().getResourceAsStream("/Fonts/OpenSans-Italic.ttf"));
            this.OpenSansItalic = OpenSans.deriveFont(Font.ITALIC, 23f);
        } catch (FontFormatException ex) {
            Logger.getLogger(FramePatient.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(FramePatient.class.getName()).log(Level.SEVERE, null, ex);
        }

        this.setLocationRelativeTo(null);
        this.setBackground(new Color(0, 0, 0, 0));
        jPanelFondo.setBackground(new Color(0xEDF0F2));
        jPanelAgregarPaciente.setVisible(false);
        jPanelAgregarPaciente.setBackground(Color.WHITE);
        jPanelVerPaciente.setVisible(false);
        jPanelVerPaciente.setBackground(Color.WHITE);
        jTablePatient.setDefaultEditor(Object.class, null);

        Font font = new Font("Segoe UI Semilight", Font.ITALIC, 18);
        jTextFieldSearching.setFont(font);

        jTextFieldSearching.setText("Busqueda...");
        jTextFieldSearching.setForeground(new Color(153, 153, 153));
        jLblNotiDPI.setForeground(Color.red);
        jLblNotiNME.setForeground(Color.red);
        jLblNotiLNME.setForeground(Color.red);
        jLblNotiADRS.setForeground(Color.red);
        jLblNotiTEL.setForeground(Color.red);
        jLblNotiCEL.setForeground(Color.red);
        jLblNotiFechaNac.setForeground(Color.red);

        Border round = new LineBorder(Color.decode("#CEF8E9"));
        Border empty = new EmptyBorder(0, 5, 0, 5);
        Border border = new CompoundBorder(round, empty);

        jTextFieldNombre.setBorder(border);
        jTextFieldApellido.setBorder(border);
        jTextFieldDirec.setBorder(border);
        jFtdTxtDPI.setBorder(border);
        jFtdTxtTEL.setBorder(border);
        jFtdTxtCEL.setBorder(border);
        jFtdTxtANIO.setBorder(border);

        jComboDia.setUI(new ComboCustomUI(0));

        jComboDia.setEditable(false);
        jComboMes.setUI(new ComboCustomUI(0));

        jComboMes.setEditable(false);

        jLblButton1 = new JLabel();
        getContentPane().add(jLblButton1, new AbsoluteConstraints(140, 80, 170, 38), 1);
        jLblButton2 = new JLabel();
        getContentPane().add(jLblButton2, new AbsoluteConstraints(140, 180, 210, 40), 1);
        jLblButton3 = new JLabel();
        getContentPane().add(jLblButton3, new AbsoluteConstraints(140, 750, 145, 40), 1);
    }

    public void setInicialComponents() {

        jTextFieldSearching.setFont(OpenSansItalic);
        jFtdTxtDPI.setFont(OpenSansItalic);
        jTextFieldNombre.setFont(OpenSansItalic);
        jTextFieldApellido.setFont(OpenSansItalic);
        jTextFieldDirec.setFont(OpenSansItalic);
        jFtdTxtTEL.setFont(OpenSansItalic);
        jFtdTxtCEL.setFont(OpenSansItalic);
        jFtdTxtANIO.setFont(OpenSansItalic);
        jComboDia.setFont(OpenSansItalic);
        jComboMes.setFont(OpenSansItalic);
        jTextFieldSearching.setForeground(Color.decode("#9B9797"));
        jFtdTxtDPI.setForeground(Color.decode("#9B9797"));
        jTextFieldNombre.setForeground(Color.decode("#9B9797"));
        jTextFieldApellido.setForeground(Color.decode("#9B9797"));
        jTextFieldDirec.setForeground(Color.decode("#9B9797"));
        jFtdTxtTEL.setForeground(Color.decode("#9B9797"));
        jFtdTxtCEL.setForeground(Color.decode("#9B9797"));
        jFtdTxtANIO.setForeground(Color.decode("#9B9797"));
        jComboDia.setForeground(Color.decode("#9B9797"));
        jComboMes.setForeground(Color.decode("#9B9797"));

        jTextFieldNombre.setBackground(Color.decode("#CEF8E9"));
        jTextFieldApellido.setBackground(Color.decode("#CEF8E9"));
        jTextFieldDirec.setBackground(Color.decode("#CEF8E9"));
        jFtdTxtDPI.setBackground(Color.decode("#CEF8E9"));
        jFtdTxtTEL.setBackground(Color.decode("#CEF8E9"));
        jFtdTxtCEL.setBackground(Color.decode("#CEF8E9"));
        jFtdTxtANIO.setBackground(Color.decode("#CEF8E9"));

        jTextFieldSearching.setText("Busqueda...");
        jTextFieldNombre.setText("Escribir Nombres...");
        jTextFieldApellido.setText("Escribir Apellidos...");
        jTextFieldDirec.setText("Escribir Direccion...");
        jFtdTxtDPI.setText("9999 99999 9999");
        jFtdTxtTEL.setText("7777 7777");
        jFtdTxtCEL.setText("5555 5555");
        jFtdTxtANIO.setText(String.valueOf(year));
        jLblNotiStatusDPI.setText("");
        jLblNotiStatusNME.setText("");
        jLblNotiStatusLNME.setText("");
        jLblNotiStatusADRS.setText("");
        jLblNotiStatusTEL.setText("");
        jLblNotiStatusCEL.setText("");
        jLblNotiDPI.setText("");
        jLblNotiNME.setText("");
        jLblNotiLNME.setText("");
        jLblNotiADRS.setText("");
        jLblNotiTEL.setText("");
        jLblNotiCEL.setText("");
        jLblNotiFechaNac.setText("");

        jLblNotiStatusDPI.setIcon(null);
        jLblNotiStatusNME.setIcon(null);
        jLblNotiStatusLNME.setIcon(null);
        jLblNotiStatusADRS.setIcon(null);
        jLblNotiStatusTEL.setIcon(null);
        jLblNotiStatusCEL.setIcon(null);
        jLblNotiStatusFechaNac.setIcon(null);

        jComboDia.removeAllItems();
        jComboMes.removeAllItems();
        jComboDia.addItem("Dia");
        jComboMes.addItem("Mes");

        for (int i = 1; i < 32; i++) {
            jComboDia.addItem(String.valueOf(i));
        }

        String[] months = new DateFormatSymbols().getMonths();
        for (int i = 0; i < months.length - 1; i++) {
            jComboMes.addItem(months[i]);
        }
    }

    private void notiOKNT(int i) {
        if (i == 1) {
            ImageIcon imgicon = new ImageIcon(getClass().getResource("/pckgPaciente/imgs/icoOK.png"));
            JLabel labelNoti = new JLabel(imgicon);
            labelNoti.setFont(OpenSans);
            labelNoti.setBackground(Color.decode("#EAFDF7"));
            labelNoti.setOpaque(true);
            labelNoti.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            labelNoti.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            jPanelAgregarPaciente.add(labelNoti, new AbsoluteConstraints(345, 285, 250, 250), 1);
            labelNoti.setText("Registro Correcto " + "()");
            PatientThread hilo = new PatientThread(labelNoti, 1);
            hilo.start();
        } else if (i == 0) {
            ImageIcon imgicon = new ImageIcon(getClass().getResource("/pckgPaciente/imgs/icoERROR.png"));
            JLabel labelNoti = new JLabel(imgicon);
            labelNoti.setFont(OpenSans);
            labelNoti.setBackground(Color.decode("#FFD0D0"));
            labelNoti.setOpaque(true);
            labelNoti.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
            labelNoti.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
            jPanelAgregarPaciente.add(labelNoti, new AbsoluteConstraints(345, 285, 250, 250), 1);
            labelNoti.setText("Registro Fallido " + "()");
            PatientThread hilo = new PatientThread(labelNoti, 0);
            hilo.start();
        }
    }

    private void reAdjustCaret(int i) {
        if (i == 1) {
            int caretPos = jFtdTxtDPI.getText().replaceAll("\\s+", "").length();
            if (caretPos > 9) {
                caretPos += 2;
            } else if (caretPos > 4) {
                caretPos += 1;
            } else {
                caretPos += 0;
            }
            jFtdTxtDPI.setCaretPosition(caretPos);
        } else if (i == 2) {
            int caretPos = jFtdTxtTEL.getText().replaceAll("\\s+", "").length();
            if (caretPos > 4) {
                caretPos += 1;
            } else {
                caretPos += 0;
            }
            jFtdTxtTEL.setCaretPosition(caretPos);
        } else if (i == 3) {
            int caretPos = jFtdTxtCEL.getText().replaceAll("\\s+", "").length();
            if (caretPos > 4) {
                caretPos += 1;
            } else {
                caretPos += 0;
            }
            jFtdTxtCEL.setCaretPosition(caretPos);
        } else if (i == 4) {
            int caretPos = jFtdTxtANIO.getText().replaceAll("\\s+", "").length();
            jFtdTxtANIO.setCaretPosition(caretPos);
        }
    }

    private boolean verificarIcons(int i) {
        if (i == 0) {
            Object dpiNull = jLblNotiStatusDPI.getIcon();
            Object nombreNull = jLblNotiStatusNME.getIcon();
            Object apellidoNull = jLblNotiStatusLNME.getIcon();
            Object direccionNull = jLblNotiStatusADRS.getIcon();
            Object telNull = jLblNotiStatusTEL.getIcon();
            Object celNull = jLblNotiStatusCEL.getIcon();
            Object fechaNacNull = jLblNotiStatusFechaNac.getIcon();

            if (dpiNull == null || nombreNull == null || apellidoNull == null
                    || direccionNull == null || telNull == null || celNull == null
                    || fechaNacNull == null) {
                return true;
            } else {
                return false;
            }
        } else {
            boolean dpiStatus = jLblNotiStatusDPI.getIcon().toString().contains("/imgs/okICO.png");
            boolean nombreStatus = jLblNotiStatusNME.getIcon().toString().contains("/imgs/okICO.png");
            boolean apellidoStatus = jLblNotiStatusLNME.getIcon().toString().contains("/imgs/okICO.png");
            boolean direccionStatus = jLblNotiStatusADRS.getIcon().toString().contains("/imgs/okICO.png");
            boolean telStatus = jLblNotiStatusTEL.getIcon().toString().contains("/imgs/okICO.png");
            boolean celStatus = jLblNotiStatusCEL.getIcon().toString().contains("/imgs/okICO.png");
            boolean fechaNacStatus = jLblNotiStatusFechaNac.getIcon().toString().contains("/imgs/okICO.png");
            if ((dpiStatus && nombreStatus && apellidoStatus && direccionStatus
                    && telStatus && celStatus && fechaNacStatus) == true) {
                System.out.println("SI");
                return true;
            } else {
                return false;
            }
        }
    }
}
